<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
    public function run()
    {
        DB::table('currencies')->insert([
            ['name' => 'Afghani', 'alphabetic_code' => 'AFN', 'numeric_code' => '971', 'minor_unit' => 2, 'fund' => '', 'symbol' => '؋'],
            ['name' => 'Euro', 'alphabetic_code' => 'EUR', 'numeric_code' => '978', 'minor_unit' => 2, 'fund' => '', 'symbol' => '€'],
            ['name' => 'Lek', 'alphabetic_code' => 'ALL', 'numeric_code' => '008', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'Lek'],
            ['name' => 'Algerian Dinar', 'alphabetic_code' => 'DZD', 'numeric_code' => '012', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'د.ج'],
            ['name' => 'US Dollar', 'alphabetic_code' => 'USD', 'numeric_code' => '840', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Kwanza', 'alphabetic_code' => 'AOA', 'numeric_code' => '973', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'Kz'],
            ['name' => 'Armenian Dram', 'alphabetic_code' => 'AMD', 'numeric_code' => '051', 'minor_unit' => 2, 'fund' => '', 'symbol' => '֏'],
            ['name' => 'Aruban Florin', 'alphabetic_code' => 'AWG', 'numeric_code' => '533', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'ƒ'],
            ['name' => 'Australian Dollar', 'alphabetic_code' => 'AUD', 'numeric_code' => '036', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Azerbaijan Manat', 'alphabetic_code' => 'AZN', 'numeric_code' => '944', 'minor_unit' => 2, 'fund' => '', 'symbol' => '₼'],
            ['name' => 'Bahamian Dollar', 'alphabetic_code' => 'BSD', 'numeric_code' => '044', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Bahraini Dinar', 'alphabetic_code' => 'BHD', 'numeric_code' => '048', 'minor_unit' => 3, 'fund' => '', 'symbol' => '.د.ب'],
            ['name' => 'Taka', 'alphabetic_code' => 'BDT', 'numeric_code' => '050', 'minor_unit' => 2, 'fund' => '', 'symbol' => '৳'],
            ['name' => 'Barbados Dollar', 'alphabetic_code' => 'BBD', 'numeric_code' => '052', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Belarusian Ruble', 'alphabetic_code' => 'BYN', 'numeric_code' => '933', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'Br'],
            ['name' => 'Belize Dollar', 'alphabetic_code' => 'BZD', 'numeric_code' => '084', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'CFA Franc BCEAO', 'alphabetic_code' => 'XOF', 'numeric_code' => '952', 'minor_unit' => 0, 'fund' => '', 'symbol' => 'Fr'],
            ['name' => 'Bermudian Dollar', 'alphabetic_code' => 'BMD', 'numeric_code' => '060', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Indian Rupee', 'alphabetic_code' => 'INR', 'numeric_code' => '356', 'minor_unit' => 2, 'fund' => '', 'symbol' => '₹'],
            ['name' => 'Ngultrum', 'alphabetic_code' => 'BTN', 'numeric_code' => '064', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'Nu.'],
            ['name' => 'Boliviano', 'alphabetic_code' => 'BOB', 'numeric_code' => '068', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'Bs'],
            ['name' => 'Mvdol', 'alphabetic_code' => 'BOV', 'numeric_code' => '984', 'minor_unit' => 2, 'fund' => 'TRUE', 'symbol' => 'Mvd'],
            ['name' => 'Convertible Mark', 'alphabetic_code' => 'BAM', 'numeric_code' => '977', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'KM'],
            ['name' => 'Pula', 'alphabetic_code' => 'BWP', 'numeric_code' => '072', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'P'],
            ['name' => 'Norwegian Krone', 'alphabetic_code' => 'NOK', 'numeric_code' => '578', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'kr'],
            ['name' => 'Brazilian Real', 'alphabetic_code' => 'BRL', 'numeric_code' => '986', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'R$'],
            ['name' => 'Bulgarian Lev', 'alphabetic_code' => 'BGN', 'numeric_code' => '975', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'лв'],
            ['name' => 'Burundi Franc', 'alphabetic_code' => 'BIF', 'numeric_code' => '108', 'minor_unit' => 0, 'fund' => '', 'symbol' => 'Fr'],
            ['name' => 'Cabo Verde Escudo', 'alphabetic_code' => 'CVE', 'numeric_code' => '132', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Riel', 'alphabetic_code' => 'KHR', 'numeric_code' => '116', 'minor_unit' => 2, 'fund' => '', 'symbol' => '៛'],
            ['name' => 'Canadian Dollar', 'alphabetic_code' => 'CAD', 'numeric_code' => '124', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Cayman Islands Dollar', 'alphabetic_code' => 'KYD', 'numeric_code' => '136', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Chilean Peso', 'alphabetic_code' => 'CLP', 'numeric_code' => '152', 'minor_unit' => 0, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Unidad de Fomento', 'alphabetic_code' => 'CLF', 'numeric_code' => '990', 'minor_unit' => 4, 'fund' => 'TRUE', 'symbol' => 'UF'],
            ['name' => 'Yuan Renminbi', 'alphabetic_code' => 'CNY', 'numeric_code' => '156', 'minor_unit' => 2, 'fund' => '', 'symbol' => '¥'],
            ['name' => 'Colombian Peso', 'alphabetic_code' => 'COP', 'numeric_code' => '170', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Unidad de Valor Real', 'alphabetic_code' => 'COU', 'numeric_code' => '970', 'minor_unit' => 2, 'fund' => 'TRUE', 'symbol' => 'UVR'],
            ['name' => 'Comorian Franc', 'alphabetic_code' => 'KMF', 'numeric_code' => '174', 'minor_unit' => 0, 'fund' => '', 'symbol' => 'Fr'],
            ['name' => 'Congolese Franc', 'alphabetic_code' => 'CDF', 'numeric_code' => '976', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'Fr'],
            ['name' => 'New Zealand Dollar', 'alphabetic_code' => 'NZD', 'numeric_code' => '554', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Costa Rican Colon', 'alphabetic_code' => 'CRC', 'numeric_code' => '188', 'minor_unit' => 2, 'fund' => '', 'symbol' => '₡'],
            ['name' => 'Cuban Peso', 'alphabetic_code' => 'CUP', 'numeric_code' => '192', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'CUC Convertible Peso', 'alphabetic_code' => 'CUC', 'numeric_code' => '931', 'minor_unit' => 2, 'fund' => 'TRUE', 'symbol' => '$'],
            ['name' => 'Czech Koruna', 'alphabetic_code' => 'CZK', 'numeric_code' => '203', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'Kč'],
            ['name' => 'Danish Krone', 'alphabetic_code' => 'DKK', 'numeric_code' => '208', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'kr'],
            ['name' => 'Djiboutian Franc', 'alphabetic_code' => 'DJF', 'numeric_code' => '262', 'minor_unit' => 0, 'fund' => '', 'symbol' => 'Fr'],
            ['name' => 'Dominican Peso', 'alphabetic_code' => 'DOP', 'numeric_code' => '214', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Egyptian Pound', 'alphabetic_code' => 'EGP', 'numeric_code' => '818', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'ج.م'],
            ['name' => 'El Salvador Colon', 'alphabetic_code' => 'SVC', 'numeric_code' => '222', 'minor_unit' => 2, 'fund' => '', 'symbol' => '₡'],
            ['name' => 'Equatorial Guinean Franc', 'alphabetic_code' => 'XAF', 'numeric_code' => '950', 'minor_unit' => 0, 'fund' => '', 'symbol' => 'Fr'],
            ['name' => 'Eritrean Nakfa', 'alphabetic_code' => 'ERN', 'numeric_code' => '232', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'Nkf'],
            ['name' => 'Estonian Kroon', 'alphabetic_code' => 'EEK', 'numeric_code' => '233', 'minor_unit' => 2, 'fund' => 'TRUE', 'symbol' => 'kr'],
            ['name' => 'Ethiopian Birr', 'alphabetic_code' => 'ETB', 'numeric_code' => '230', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'ብር'],
            ['name' => 'Falkland Islands Pound', 'alphabetic_code' => 'FKP', 'numeric_code' => '238', 'minor_unit' => 2, 'fund' => '', 'symbol' => '£'],
            ['name' => 'Faroe Islands Króna', 'alphabetic_code' => 'FOK', 'numeric_code' => '234', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'kr'],
            ['name' => 'Fijian Dollar', 'alphabetic_code' => 'FJD', 'numeric_code' => '242', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Gabonese Franc', 'alphabetic_code' => 'XAF', 'numeric_code' => '950', 'minor_unit' => 0, 'fund' => '', 'symbol' => 'Fr'],
            ['name' => 'Gambian Dalasi', 'alphabetic_code' => 'GMD', 'numeric_code' => '270', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'D'],
            ['name' => 'Georgian Lari', 'alphabetic_code' => 'GEL', 'numeric_code' => '981', 'minor_unit' => 2, 'fund' => '', 'symbol' => '₾'],
            ['name' => 'German Mark', 'alphabetic_code' => 'DEM', 'numeric_code' => '276', 'minor_unit' => 2, 'fund' => 'TRUE', 'symbol' => 'DM'],
            ['name' => 'Ghanaian Cedi', 'alphabetic_code' => 'GHS', 'numeric_code' => '936', 'minor_unit' => 2, 'fund' => '', 'symbol' => '₵'],
            ['name' => 'Gibraltar Pound', 'alphabetic_code' => 'GIP', 'numeric_code' => '292', 'minor_unit' => 2, 'fund' => '', 'symbol' => '£'],
            ['name' => 'Greek Drachma', 'alphabetic_code' => 'GRD', 'numeric_code' => '300', 'minor_unit' => 2, 'fund' => 'TRUE', 'symbol' => '₯'],
            ['name' => 'Guatemalan Quetzal', 'alphabetic_code' => 'GTQ', 'numeric_code' => '320', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'Q'],
            ['name' => 'Guinean Franc', 'alphabetic_code' => 'GNF', 'numeric_code' => '324', 'minor_unit' => 0, 'fund' => '', 'symbol' => 'Fr'],
            ['name' => 'Guyanaese Dollar', 'alphabetic_code' => 'GYD', 'numeric_code' => '328', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Haitian Gourde', 'alphabetic_code' => 'HTG', 'numeric_code' => '332', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'G'],
            ['name' => 'Honduran Lempira', 'alphabetic_code' => 'HNL', 'numeric_code' => '340', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'L'],
            ['name' => 'Hong Kong Dollar', 'alphabetic_code' => 'HKD', 'numeric_code' => '344', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Hungarian Forint', 'alphabetic_code' => 'HUF', 'numeric_code' => '348', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'Ft'],
            ['name' => 'Icelandic Króna', 'alphabetic_code' => 'ISK', 'numeric_code' => '352', 'minor_unit' => 0, 'fund' => '', 'symbol' => 'kr'],
            ['name' => 'Indian Rupee', 'alphabetic_code' => 'INR', 'numeric_code' => '356', 'minor_unit' => 2, 'fund' => '', 'symbol' => '₹'],
            ['name' => 'Iranian Rial', 'alphabetic_code' => 'IRR', 'numeric_code' => '364', 'minor_unit' => 2, 'fund' => '', 'symbol' => '﷼'],
            ['name' => 'Iraqi Dinar', 'alphabetic_code' => 'IQD', 'numeric_code' => '368', 'minor_unit' => 3, 'fund' => '', 'symbol' => 'ع.د'],
            ['name' => 'Irish Pound', 'alphabetic_code' => 'IEP', 'numeric_code' => '372', 'minor_unit' => 2, 'fund' => 'TRUE', 'symbol' => '£'],
            ['name' => 'Israeli New Shekel', 'alphabetic_code' => 'ILS', 'numeric_code' => '376', 'minor_unit' => 2, 'fund' => '', 'symbol' => '₪'],
            ['name' => 'Italian Lira', 'alphabetic_code' => 'ITL', 'numeric_code' => '380', 'minor_unit' => 2, 'fund' => 'TRUE', 'symbol' => '₯'],
            ['name' => 'Jamaican Dollar', 'alphabetic_code' => 'JMD', 'numeric_code' => '388', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Japanese Yen', 'alphabetic_code' => 'JPY', 'numeric_code' => '392', 'minor_unit' => 0, 'fund' => '', 'symbol' => '¥'],
            ['name' => 'Jordanian Dinar', 'alphabetic_code' => 'JOD', 'numeric_code' => '400', 'minor_unit' => 3, 'fund' => '', 'symbol' => 'د.ا'],
            ['name' => 'Kazakhstani Tenge', 'alphabetic_code' => 'KZT', 'numeric_code' => '398', 'minor_unit' => 2, 'fund' => '', 'symbol' => '₸'],
            ['name' => 'Kenyan Shilling', 'alphabetic_code' => 'KES', 'numeric_code' => '404', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'KSh'],
            ['name' => 'Kiribati Dollar', 'alphabetic_code' => 'KID', 'numeric_code' => '296', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Kuwaiti Dinar', 'alphabetic_code' => 'KWD', 'numeric_code' => '414', 'minor_unit' => 3, 'fund' => '', 'symbol' => 'د.ك'],
            ['name' => 'Kyrgystani Som', 'alphabetic_code' => 'KGS', 'numeric_code' => '417', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'лв'],
            ['name' => 'Lao Kip', 'alphabetic_code' => 'LAK', 'numeric_code' => '418', 'minor_unit' => 2, 'fund' => '', 'symbol' => '₭'],
            ['name' => 'Latvian Lats', 'alphabetic_code' => 'LVL', 'numeric_code' => '428', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'Ls'],
            ['name' => 'Lebanese Pound', 'alphabetic_code' => 'LBP', 'numeric_code' => '422', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'ل.ل'],
            ['name' => 'Lesotho Loti', 'alphabetic_code' => 'LSL', 'numeric_code' => '426', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'L'],
            ['name' => 'Liberian Dollar', 'alphabetic_code' => 'LRD', 'numeric_code' => '430', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Libyan Dinar', 'alphabetic_code' => 'LYD', 'numeric_code' => '434', 'minor_unit' => 3, 'fund' => '', 'symbol' => 'د.ل'],
            ['name' => 'Lotus', 'alphabetic_code' => 'LKR', 'numeric_code' => '144', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'Rs'],
            ['name' => 'Macanese Pataca', 'alphabetic_code' => 'MOP', 'numeric_code' => '446', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'P'],
            ['name' => 'Malagasy Ariary', 'alphabetic_code' => 'MGA', 'numeric_code' => '969', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'Ar'],
            ['name' => 'Malawi Kwacha', 'alphabetic_code' => 'MWK', 'numeric_code' => '454', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'MK'],
            ['name' => 'Malaysian Ringgit', 'alphabetic_code' => 'MYR', 'numeric_code' => '458', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'RM'],
            ['name' => 'Mauritanian Ouguiya', 'alphabetic_code' => 'MRU', 'numeric_code' => '478', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'UM'],
            ['name' => 'Mauritian Rupee', 'alphabetic_code' => 'MUR', 'numeric_code' => '480', 'minor_unit' => 2, 'fund' => '', 'symbol' => '₨'],
            ['name' => 'Mexican Peso', 'alphabetic_code' => 'MXN', 'numeric_code' => '484', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Mexican Unidad de Inversion', 'alphabetic_code' => 'MXV', 'numeric_code' => '979', 'minor_unit' => 2, 'fund' => 'TRUE', 'symbol' => 'UDI'],
            ['name' => 'Moldovan Leu', 'alphabetic_code' => 'MDL', 'numeric_code' => '498', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'L'],
            ['name' => 'Mongolian Tugrik', 'alphabetic_code' => 'MNT', 'numeric_code' => '496', 'minor_unit' => 2, 'fund' => '', 'symbol' => '₮'],
            ['name' => 'Moroccan Dirham', 'alphabetic_code' => 'MAD', 'numeric_code' => '504', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'د.م.'],
            ['name' => 'Moldovan Leu', 'alphabetic_code' => 'MDL', 'numeric_code' => '498', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'L'],
            ['name' => 'Nepalese Rupee', 'alphabetic_code' => 'NPR', 'numeric_code' => '524', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'Rs'],
            ['name' => 'Netherlands Antillean Guilder', 'alphabetic_code' => 'ANG', 'numeric_code' => '532', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'ƒ'],
            ['name' => 'New Zealand Dollar', 'alphabetic_code' => 'NZD', 'numeric_code' => '554', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Nigerian Naira', 'alphabetic_code' => 'NGN', 'numeric_code' => '566', 'minor_unit' => 2, 'fund' => '', 'symbol' => '₦'],
            ['name' => 'North Korean Won', 'alphabetic_code' => 'KPW', 'numeric_code' => '408', 'minor_unit' => 2, 'fund' => '', 'symbol' => '₩'],
            ['name' => 'Norwegian Krone', 'alphabetic_code' => 'NOK', 'numeric_code' => '578', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'kr'],
            ['name' => 'Omani Rial', 'alphabetic_code' => 'OMR', 'numeric_code' => '512', 'minor_unit' => 3, 'fund' => '', 'symbol' => 'ر.ع.'],
            ['name' => 'Pakistani Rupee', 'alphabetic_code' => 'PKR', 'numeric_code' => '586', 'minor_unit' => 2, 'fund' => '', 'symbol' => '₨'],
            ['name' => 'Papua New Guinean Kina', 'alphabetic_code' => 'PGK', 'numeric_code' => '598', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'K'],
            ['name' => 'Paraguayan Guarani', 'alphabetic_code' => 'PYG', 'numeric_code' => '600', 'minor_unit' => 0, 'fund' => '', 'symbol' => '₲'],
            ['name' => 'Peruvian Nuevo Sol', 'alphabetic_code' => 'PEN', 'numeric_code' => '604', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'S/'],
            ['name' => 'Philippine Peso', 'alphabetic_code' => 'PHP', 'numeric_code' => '608', 'minor_unit' => 2, 'fund' => '', 'symbol' => '₱'],
            ['name' => 'Pakistani Rupee', 'alphabetic_code' => 'PKR', 'numeric_code' => '586', 'minor_unit' => 2, 'fund' => '', 'symbol' => '₨'],
            ['name' => 'Polish Zloty', 'alphabetic_code' => 'PLN', 'numeric_code' => '985', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'zł'],
            ['name' => 'Qatari Rial', 'alphabetic_code' => 'QAR', 'numeric_code' => '634', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'ر.ق'],
            ['name' => 'Romanian Leu', 'alphabetic_code' => 'RON', 'numeric_code' => '946', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'lei'],
            ['name' => 'Russian Ruble', 'alphabetic_code' => 'RUB', 'numeric_code' => '643', 'minor_unit' => 2, 'fund' => '', 'symbol' => '₽'],
            ['name' => 'Rwandan Franc', 'alphabetic_code' => 'RWF', 'numeric_code' => '646', 'minor_unit' => 0, 'fund' => '', 'symbol' => 'Fr'],
            ['name' => 'Saint Helena Pound', 'alphabetic_code' => 'SHP', 'numeric_code' => '654', 'minor_unit' => 2, 'fund' => '', 'symbol' => '£'],
            ['name' => 'Samoan Tala', 'alphabetic_code' => 'WST', 'numeric_code' => '882', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'T'],
            ['name' => 'San Marinese Lira', 'alphabetic_code' => 'SML', 'numeric_code' => '674', 'minor_unit' => 2, 'fund' => 'TRUE', 'symbol' => '₯'],
            ['name' => 'Sao Tome and Principe Dobra', 'alphabetic_code' => 'STN', 'numeric_code' => '678', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'Db'],
            ['name' => 'Saudi Riyal', 'alphabetic_code' => 'SAR', 'numeric_code' => '682', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'ر.س'],
            ['name' => 'Serbian Dinar', 'alphabetic_code' => 'RSD', 'numeric_code' => '941', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'дин.'],
            ['name' => 'Seychellois Rupee', 'alphabetic_code' => 'SCR', 'numeric_code' => '690', 'minor_unit' => 2, 'fund' => '', 'symbol' => '₨'],
            ['name' => 'Sierra Leonean Leone', 'alphabetic_code' => 'SLL', 'numeric_code' => '694', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'Le'],
            ['name' => 'Singapore Dollar', 'alphabetic_code' => 'SGD', 'numeric_code' => '702', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Solomon Islands Dollar', 'alphabetic_code' => 'SBD', 'numeric_code' => '090', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Somali Shilling', 'alphabetic_code' => 'SOS', 'numeric_code' => '706', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'Sh'],
            ['name' => 'South African Rand', 'alphabetic_code' => 'ZAR', 'numeric_code' => '710', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'R'],
            ['name' => 'South Korean Won', 'alphabetic_code' => 'KRW', 'numeric_code' => '410', 'minor_unit' => 0, 'fund' => '', 'symbol' => '₩'],
            ['name' => 'South Sudanese Pound', 'alphabetic_code' => 'SSP', 'numeric_code' => '728', 'minor_unit' => 2, 'fund' => '', 'symbol' => '£'],
            ['name' => 'Spanish Peseta', 'alphabetic_code' => 'ESP', 'numeric_code' => '998', 'minor_unit' => 2, 'fund' => 'TRUE', 'symbol' => '₧'],
            ['name' => 'Sri Lankan Rupee', 'alphabetic_code' => 'LKR', 'numeric_code' => '144', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'Rs'],
            ['name' => 'Sierra Leonean Leone', 'alphabetic_code' => 'SLL', 'numeric_code' => '694', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'Le'],
            ['name' => 'Sudanese Pound', 'alphabetic_code' => 'SDG', 'numeric_code' => '938', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'ج.س'],
            ['name' => 'Surinamese Dollar', 'alphabetic_code' => 'SRD', 'numeric_code' => '968', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Swedish Krona', 'alphabetic_code' => 'SEK', 'numeric_code' => '752', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'kr'],
            ['name' => 'Swiss Franc', 'alphabetic_code' => 'CHF', 'numeric_code' => '756', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'CHF'],
            ['name' => 'Syrian Pound', 'alphabetic_code' => 'SYP', 'numeric_code' => '760', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'ل.س'],
            ['name' => 'Tajikistani Somoni', 'alphabetic_code' => 'TJS', 'numeric_code' => '972', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'ЅМ'],
            ['name' => 'Tanzanian Shilling', 'alphabetic_code' => 'TZS', 'numeric_code' => '834', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'TSh'],
            ['name' => 'Thai Baht', 'alphabetic_code' => 'THB', 'numeric_code' => '764', 'minor_unit' => 2, 'fund' => '', 'symbol' => '฿'],
            ['name' => 'Tonga Paʻanga', 'alphabetic_code' => 'TOP', 'numeric_code' => '776', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'T$'],
            ['name' => 'Trinidad and Tobago Dollar', 'alphabetic_code' => 'TTD', 'numeric_code' => '780', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Tunisian Dinar', 'alphabetic_code' => 'TND', 'numeric_code' => '788', 'minor_unit' => 3, 'fund' => '', 'symbol' => 'د.ت'],
            ['name' => 'Turkish Lira', 'alphabetic_code' => 'TRY', 'numeric_code' => '949', 'minor_unit' => 2, 'fund' => '', 'symbol' => '₺'],
            ['name' => 'Turkmenistani Manat', 'alphabetic_code' => 'TMT', 'numeric_code' => '934', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'T'],
            ['name' => 'Ugandan Shilling', 'alphabetic_code' => 'UGX', 'numeric_code' => '800', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'USh'],
            ['name' => 'Ukrainian Hryvnia', 'alphabetic_code' => 'UAH', 'numeric_code' => '980', 'minor_unit' => 2, 'fund' => '', 'symbol' => '₴'],
            ['name' => 'United Arab Emirates Dirham', 'alphabetic_code' => 'AED', 'numeric_code' => '784', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'د.إ'],
            ['name' => 'United States Dollar', 'alphabetic_code' => 'USD', 'numeric_code' => '840', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Uruguayan Peso', 'alphabetic_code' => 'UYU', 'numeric_code' => '858', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$'],
            ['name' => 'Uzbekistani Som', 'alphabetic_code' => 'UZS', 'numeric_code' => '860', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'лв'],
            ['name' => 'Vanuatu Vatu', 'alphabetic_code' => 'VUV', 'numeric_code' => '548', 'minor_unit' => 0, 'fund' => '', 'symbol' => 'Vt'],
            ['name' => 'Venezuelan Bolívar', 'alphabetic_code' => 'VES', 'numeric_code' => '928', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'Bs'],
            ['name' => 'Vietnamese Dong', 'alphabetic_code' => 'VND', 'numeric_code' => '704', 'minor_unit' => 0, 'fund' => '', 'symbol' => '₫'],
            ['name' => 'Yemeni Rial', 'alphabetic_code' => 'YER', 'numeric_code' => '886', 'minor_unit' => 2, 'fund' => '', 'symbol' => '﷼'],
            ['name' => 'Zambian Kwacha', 'alphabetic_code' => 'ZMW', 'numeric_code' => '967', 'minor_unit' => 2, 'fund' => '', 'symbol' => 'ZK'],
            ['name' => 'Zaire', 'alphabetic_code' => 'ZRZ', 'numeric_code' => '180', 'minor_unit' => 2, 'fund' => 'TRUE', 'symbol' => 'Z'],
            ['name' => 'Zimbabwean Dollar', 'alphabetic_code' => 'ZWL', 'numeric_code' => '932', 'minor_unit' => 2, 'fund' => '', 'symbol' => '$']
        ]);
    }
}
